2025-04-24 11:27:50 | WARNING  | file_checker | Chiave non riconosciuta nelle specifiche: 1x edizione volume
2025-04-24 11:27:50 | ERROR    | file_checker | Errore AnalysisWorker: 'Specifiche' object has no attribute '__dict__'
Traceback (most recent call last):
  File "file_checker\gui\worker.py", line 45, in run
AttributeError: 'Specifiche' object has no attribute '__dict__'. Did you mean: '__dir__'?
2025-04-24 11:27:56 | ERROR    | file_checker | Errore AnalysisWorker: 'Specifiche' object has no attribute '__dict__'
Traceback (most recent call last):
  File "file_checker\gui\worker.py", line 45, in run
AttributeError: 'Specifiche' object has no attribute '__dict__'. Did you mean: '__dir__'?
2025-04-24 11:28:04 | ERROR    | file_checker | Errore AnalysisWorker: 'Specifiche' object has no attribute '__dict__'
Traceback (most recent call last):
  File "file_checker\gui\worker.py", line 45, in run
AttributeError: 'Specifiche' object has no attribute '__dict__'. Did you mean: '__dir__'?
